name: Matrix Workflow
on: push
jobs:
  node-version:
    runs-on: ubuntu-latest
    steps:
      - name: Log node versions
        run: node -v
      - uses: actions/setup-node@v3
        with:
          node-version: 6
      - name: Log node versions
        run: node -v
